== Introduction and Goals

[[section-introduction-and-goals]]
Radarin es una aplicación que tiene como objetivo facilitar los encuentros entre personas que se encuentren en un mismo area.
La aplicación tiene una serie de requerimientos de acceso sobre datos como la localización del usuario (la cual puede activar o no voluntariamente), 
la cual permitira a los usuarios conocer la ubicación de sus contactos cuando estos se encuentren cerca.

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.

* Se podrá conocer la ubicación de los usuarios en cada momento
* Consultar los contactos de cada usuario para poder relacionarlos
* Ofrecer la opcion de añadir comentarios y contenido multimedia en las localizaciones
* El usuario podrá visualizar los mapas
* Los usuarios podrán marcar ciertas localizaciones
* Los usuarios podrán ponerse en contacto a través de un chat de la aplicación

****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities

[options="header",cols="1,2"]
|===
|Quality Goals|Concrete Scenaries
| _Usabilidad_ | La aplicación debe poder ser usada sin problemas por todos los posibles usuarios.
| _Privacidad y seguridad_ | Se guardarán solamente los datos necesarios de cada usuario, el resto de cogerán cuando sean necesarios del dispositivo del usuario. A demás, este podrá activar y desactivar la ubicación cuando lo desee y la aplicación no podrá ver este dato.
| _Testabilidad_ | El funcionamiento de la aplicación podrá ser probado fácilmente.
|

****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Comunidad de SOLID_ | _Equipo de SOLID_ | _Esperan que se siga las especificaciones SOLID_
| _Equipo_ | _Equipo de Desarrollo_ | _Esperan desarrollar la aplicación correctamente, compenetrarse bien y trabajar en equipo para lograr el objetivo._
| _Usuarios_ | _Potenciales usuarios de la aplicación_ | _Esperan que la aplicación funcione correctamente y que cumpla con su compromiso de mantener su privacidad._
|===
