[[section-architecture-constraints]]
== Architecture Constraints

=== Thechnical Constraints
[options="header",cols="1,2"]
|===
|Restricción|Explicación
| SOLID | _<Contact-1>_
| Docker | _<Contact-2>_
| Heroku | _<Contact-2>_
|===

=== Organizational Constraints
[options="header",cols="1,2"]
|===
|Restricción|Explicación
| _<Role-2>_ | _<Contact-2>_
|===

=== Political Constraints
[options="header",cols="1,2"]
|===
|Restricción|Explicación
| _<Role-2>_ | _<Contact-2>_
|===

[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
