[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.
****

The proyect idea is create a application using solid which allow us to get the localization of our friends
that are using the app.
All the information will be saved in pods, excepting the essential to the application funcionality


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****



The communication members will be:

	1.The user who share the information about his localization.

	2.The application who resend the information to his friends

	3.The user who receives the localization of a friend to see where he is

	4.The pods in which the application look for who the user has added
	
	


=== Technical Context

[role="arc42help"]
****
.Contents
.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

To develop this application, we are going to use SOLID to allow us to use private information of the users, without us needing to store it, which helps achieve our goal of user-friendly application that respects privacy.
Other technologies that we are going to use are React Native and Nodejs. These two libraries for JavaScript, will help us develop the communication with SOLID pods and the IGU.
