[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****


To the application developtment we are going to use JavaScript with the React library 
due to it has some components which allow us work easier with Solid and it make simpler
the use of JavaScript. Also because its relatively easy to learn and exists a lot of
documentation about it, what makes it very adequate for people who don't have experience with
this type of applications.

In order to have more security with application changes the team will have a comun branch 
to work called "develop" to integrate the work, having the main branch only to stable versions.

We are going to use MongoDB to persist the location of users, the rest of information will be saved
in pods, the localizations will have a expire time of one minit to be secure that a user dont forget
shut down his app .

We are going to use Mapbox Api to show users Localization in a map, this map is refreshed every 5 seconds with "react-interval-renderer".
In each refresh we save user localization, we get friends localizations and we show the notifications to the user, having a "real time map"

react-push-notification is the module choosed to show notifications when your friend start the app or enter in your area, due to its a very
customizable component and easy to understand the basics.

In order to make the app compatible with solid we use two modules ,first @Solid/react because provide a simple implementation to login 
in solid and get your  added friends, however we use also @solid/query-ldflex because make easier obtain more complex data, for example
names and surnames.