[[section-building-block-view]]
== Building Block View
=== Whitebox Overall System
=== Level 1

[plantuml, "block level 1", png]
----
@startuml
Node "Level 1" {
actor User
rectangle App
database MongoDB
database Pods
}
App <-up->  User
App <-down-> MongoDB
App <-down-> Pods
@enduml
----

Motivation::
El usuario interacciona con nuestra App, la cual a su vez usa una base de datos MongoDB y el POD de SOLID del usuario.

Contained Building Blocks::
[cols="1,2" options="header"]
|===
| **Name** | **Responsibility**
| User | User of the app. Will interact with the App.
| App | Web application that connects with the MongoDB database and with the PODs of the users of the application.
| MongoDB | NoSQL database that stores the locations of the users that allow it. The locations won't be stored for longer than a minute.
| POD | SOLID PODs where the user's of the application store their data.
|===

==== Level 2
==== White Box _App_

[plantuml, "block level 2", png]
----
@startuml
Node "Level 2: App" as WebApp2 {
rectangle "E2E testing"
rectangle "docs"
rectangle "WebApp" as react
rectangle "Restapi"
}
react <--> Restapi
@enduml
----

Motivation::
La WebApp utiliza la Restapi para conectarse con la base de datos en MongoDB.


Contained Building Blocks::
[cols="1,2" options="header"]
|===
| **Name** | **Responsibility**
| WebApp | Aplicación en react y nodejs 
| Restapi | aplicacion que conecta con la base de datos
| docs | Documentación de la aplicación
| E2E testing | _<Text>_
|===

==== Level 3
==== White Box _WebApp_

[plantuml, "block level 2", png]
----
@startuml
Node "Level 3: WebApp" as WebApp3 {
rectangle "Localization"
rectangle "Views"
rectangle "FriendList"
rectangle "Admin"
rectangle "Notifications"
}
Localization <--> Notifications
@enduml
----

Motivation::



Contained Building Blocks::
[cols="1,2" options="header"]
|===
| **Name** | **Responsibility**
| Localization | _<Text>_
| Views | _<Text>_
| FriendList | _<Text>_
| Admin | _<Text>_
| Notifications | _<Text>_
|===

