[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
=== Log In Scenario


The first interaction the user has with the application is the log in process.

Once the user clicks the 'LogIn' button, the application will redirect the user to a SOLID login webpage, which will manage the process from here. 

Only when the login it's been a success, the SOLID webpage popup will redirect the user back to the app. The app will detect that the user is properly logged in and it will load the new content to display.


[plantuml,"login diagram",png]
----
@startuml
actor User #red
participant App
database SOLIDprovider #blue
User -[#green]> App: Log In user
App -[#blue]> SOLIDprovider: Log In new user (req)
App <[#blue]-- SOLIDprovider: Log In response
App --> App: Load Welcome View
@enduml
----

=== Friends Location Scenario


The most relevant scenario of the application is the feature that allows to locate friends.

Once the user is logged in, he will be able to ask the application for his friends location. 

The app will show the list of friends with their latest known location.


[plantuml,"location diagram",png]
----
@startuml
actor User #red
participant App
database UserPOD #red
database MongoDB #blue
App <[#blue]--  User: Switch on app
App -[#blue]>  User: User location (req)
App <[#blue]--  User: User location (res)
App -[#blue]> MongoDB: Save user location
User -[#green]> App: Find Friends (req)
App -> UserPOD: Friends list (req)
App <-- UserPOD: Friends list (res)
App -[#blue]> MongoDB: Friends location (req)
App <[#blue]-- MongoDB: Friends location (res)
App -> App: Calculate distance
App --[#green]> User: Notify close friends

@enduml
----


