[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
=== Log In Scenario


The first interaction the user has with the application is the log in process.

Once the user clicks the 'LogIn' button, the application will redirect the user to a SOLID login webpage, which will manage the process from here. 

Only when the login has been a success, the SOLID webpage popup will redirect the user back to the app. The app will detect that the user is properly logged in and it will load the new content to display.


[plantuml,"login diagram",png]
----
@startuml
actor User #red
participant App
database SOLIDprovider #blue
User -[#green]> App: Log In user
App -[#blue]> SOLIDprovider: Log In new user (req)
App <[#blue]-- SOLIDprovider: Log In response
App --> App: Load Welcome View
@enduml
----

=== Log Out Scenario


From every view of the application the user is able to log out.

Once the user clicks the 'LogOut' button, the application will inform the user with a message stating the he's been successfully disconnected. 


[plantuml,"logout diagram",png]
----
@startuml
actor User #red
participant App
User -[#green]> App: Log Out
App --> App: Logged Out message
@enduml
----

=== Friends Location Scenario


The most relevant scenario of the application is the feature that allows to locate friends.

Once the user is logged in, they will be able to ask the application for their friends location. 

The app will show the locations of the user's friends on a map with their latest known location.


[plantuml,"location diagram",png]
----
@startuml
actor User #red
participant App
database UserPOD #red
database MongoDB #blue
App <[#blue]--  User: Switch on app
App -[#blue]>  User: User location (req)
App <[#blue]--  User: User location (res)
App -[#blue]> MongoDB: Save user location
App -> UserPOD: Friends list (req)
App <-- UserPOD: Friends list (res)
App -[#blue]> MongoDB: Friends location (req)
App <[#blue]-- MongoDB: Friends location (res)
App -> App: Calculate distance
App -> App: Show friend's notifications on map
App --[#green]> User: Notify close friends
@enduml
----

=== Friend List

Our application allows the user to check the friends they have added in their SOLID POD.

[plantuml, "friend list", png]
----
@startuml
actor User #red
participant App
database SOLIDprovider #blue
User -[#green]> App: Friend list (req)
App -[#blue]> SOLIDprovider: Friend list (req)
App <[#blue]-- SOLIDprovider: Friend list response
User <[#green]-- App: Friend list response
@enduml
----

=== Add and Remove Friends

The user will be able to add and remove friends from their SOILD POD. Our application can communicate with the user's POD SOLID provider, which will manage the friends from the user's POD.

To request the addition or removal of a friend, the user must provide the webID from said friend.

[plantuml, "add and remove friends",png]
----
@startuml
actor User #red
participant App
database SOLIDprovider #blue
User -[#green]> App: Remove friend (webID)
App -[#blue]> SOLIDprovider: Remove friend (webID)
App <[#blue]-- SOLIDprovider: Updated friends list
User <[#green]-- App: Updated friends list
User -[#green]> App: Add friend (webID)
App -[#blue]> SOLIDprovider: Add friend (webID)
App <[#blue]-- SOLIDprovider: Updated friends list
User <[#green]-- App: Updated friends list
@enduml
----


=== Admin Scenario


The application's administrator will be able to manage data and permission through its own component.

First, he'll need to be logged in providing his credentials (username and password). 

Once logged in, several features available only for administrators will be display for him to interact with, together with a map showing the current users connected.


[plantuml,"admin",png]
----
@startuml
actor Admin #red
participant App
database MongoDB #blue
App <[#blue]--  Admin: Log in
App -[#blue]> MongoDB: Check credentials
App <[#blue]-- MongoDB: Authenticate
App -> App: Render Admin View
App -[#blue]> MongoDB: getUsersPositions
App <[#blue]-- MongoDB: usersPositions
App -> App: Render Map with users
App --[#green]> Admin: Display Map
@enduml
----

