[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Friends Location Scenario


The most relevant scenario of the application is the feature that allows to locate friends.

Once the user is logged in, he will be able to ask the application for his friends location. 

The app will show the list of friends with their latest known location.


[plantuml,"location diagram",png]
----
@startuml
actor User #red
participant App
database UserPOD #red
database MongoDB #blue
User -[#green]> App: Buscar Amigos (req)
App -> UserPOD: Lista de amigos (req)
App <-- UserPOD: Lista de amigos (res)
App -[#blue]> MongoDB: Localización de amigos (req)
App <[#blue]-- MongoDB: Localización de amigos (res)
App -[#blue]>  User: Localización usuario (req)
App <[#blue]--  User: Localización usuario (res)
App -> App: Calcular distancia de amigos
App --[#green]> User: Amigos cercanos
App -[#blue]> MongoDB: Añadir localización
@enduml
----
=== User Registration Scenario

A user must be registered in order to use the application  

The registration process will create a Solid ID for the user to be identified in future interactions with the application  

This feature will be based in Solid requirements for registering users

[plantuml,"registration diagram",png]
----
@startuml
actor User #red
participant App
database MongoDB #blue
User -[#green]> App: Registrar usuario
App -[#blue]> MongoDB: Register new user (req)
App <[#blue]-- MongoDB: Registration response
User <[#green]- App: Notificación de registro 
@enduml
----
=== Add New Friend Scenario

The application will allow the user to add friends to his friend list

When the user requests the application to add a new friend, the application will ask the user for his friend's ID.

The application will then try to add this friend to the user's POD (in case that friend is not already in the user's friend list)

The user will receive feedback once the process is done (either success or failure) by showing the friend's list.

[plantuml,"friend diagram",png]
----
@startuml
actor User #red
participant App
database UserPOD #red
User -[#green]> App: Añadir Amigo
App --[#green]> User: Pedir datos
User -[#green]> App:Enviar datos
App -> UserPOD: add (amigo)
App <-- UserPOD: Lista de amigos
App --[#green]> User: Mostrar amigos
@enduml
----

