[[section-concepts]]
== Cross-cutting Concepts

=== Domain Concepts:
*POD: The repository which make the app compatible with solid, we store all the information of a user, except the localization which is saved in mongoDB due to the efiency

*Friend: Is a person who we have added in SOLID and we can see his localization.

*Visible area: Is the area where we want see connected friends, we can parameterize it setting the radio under the map.

*Administrator: A profile where a person can access, he has more control in the app configuring and updating the database. All users can get the administrator
rol if they hace the credentials



=== User Experience 
We will try to make the interface as easy to use as we can, to simplify the app to the users, making a side menu to navigate across the app. 
However we choosed having a administrator section in the App IGU to make easier to acess and continue improving it, it maybe will change in future releases .


=== Securiy & Safety
In order to make safer the private info it will be stored in pods. 

When the user close the app the Localization is deleted from the MongoDb database, as extra security measure the localization is deleted a minit after it stops
to recieve updates securing that the user doesnt forget close his app.

The credentials of the admin role are encripted in the database.

 

=== Development concepts
We use  the Node.js packae manager to build the app ussing differents components in order to get the desired funcionality.

We use Jest to test the correct app peerformance.

We use MongoDB database to store users Localization using a restApi to connect the app.

Its possible configure a little the app  modifying the your visible area and creating meeting places.

=== Under-the-hood
*Peristency: The app use mongoDB database to store localizations and Pods to store the other information.

*Session handling: Sessions are managed with Solid (logged with Solid account) with the exception of the session administrator.

*Exception and error Handling:The biggest and most common error with the app is when geolocalization dosent work well giving your friends wrong information.

*Parallelization: The app works in notifications and localizations-reads at the same time the map is being refreshed, this can induce to some inconsistencies

between notifications and appearance of a friend markers, but produces a better efficienvy

=== Operation concepts
*Administration and Management: A person can access to admin view if he has credentials, allowing him to manage the app

*Disaster-Reovery: After some minits of doesnt receive updates the database and all stored info is cleaned.

 








